### ISSUE TITLE
Inputs vs outputs?

### ISSUE THREAD

**Issue by Boffinboy** [springfall2008/predai#4]
A fascinating addition - which I am keen to test out! Before I do that I was trying to understand what are taken as inputs to forecast? Does or take all HA sensors to predict the specified ones in the YAML? Or take all the sensors in the YAML to predict each other (eg if you put sunshine, temperature and power usage in there, it would use all three to generated predicted values of each other)? Or are the predictions “internal” ie it only looks at the historic data for a the specified sensor itself (historic load is the only sensor used to predict load)?

**Comment by springfall2008** [comment]
It's pretty simplistic right now it just uses the specified sensor for the prediction. In future it maybe possible to include other data. The historical data of that sensor is used for the prediction.

**Comment by Boffinboy** [comment]
Thank you. Will take a look and see how it maps with just the historic load.
