### ISSUE TITLE
Chart not resetting each day since 1.1.7

### ISSUE THREAD

**Issue by laurence600** [springfall2008/predai#8]
Since 1.1.7 my chart isnt resetting each day
![image](https://github.com/springfall2008/predai/assets/162343223/2a237fde-55f4-4114-b532-b1ca6e6aa9e4)

These are my settings (Ive starred out the givtcp code) -

# Example configurations are below, you must set up your own sensors
update_every: 30
sensors:
  - name: sensor.givtcp_*********_load_energy_today_kwh
    days: 14
    incrementing: True
    reset_daily: True
    interval: 30
    units: kWh
    future_periods: 96
    database: True

**Comment by springfall2008** [comment]
Is this stil an issue?

**Comment by laurence600** [comment]
No, seemed to fix itself a few releases ago
